SIM = verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = /home/james/https---github.com-JamesRyanV1-RV32I-Single-Cycle-capstone/cpu/control.sv
TOPLEVEL = control
MODULE = control
include $(shell cocotb-config --makefiles)/Makefile.sim

VERILATOR_FLAGS += -sv

#		works
#registerFile
#decoder
#alu (passes for add, other operations relativly simple to add)
#Sign Extender
#Data Memory
#Control
